In [1]:
import gymnasium as gym
import foraging_envs


env = gym.make("foraging_envs/foraging-two", episode_length = 100, flower_distribution = "uniform", decay_parameter = .25, travel_time = 2, render_mode = "human")
obs, info = env.reset()


In [2]:
env.step(0)

(array([0.       , 0.7788008], dtype=float32),
 np.float64(0.7788007830714049),
 False,
 False,
 {})

In [4]:
env.step(1)

(array([ 1.        , -0.71428573], dtype=float32),
 -0.7142857142857143,
 False,
 False,
 {})

In [5]:
env.step(0)

(array([0.       , 0.7788008], dtype=float32),
 np.float64(0.7788007830714049),
 False,
 False,
 {})